//package sample
//
//import com.laher.drools.supermarket.entity.Order
//
//rule "满足200减少30"
//    activation-group "preferential"
//    salience 5
//when
//    $order:Order(money>=200)
//then
//    $order.setPreferential(30);
//    $order.setPay($order.getMoney()-$order.getPreferential());
//    System.out.println("触发规则，计算完成 "+$order.toString());
//end
//
//rule "无优惠"
//when
//    $order:Order(money<200)
//then
//    $order.setPreferential(0);
//    $order.setPay($order.getMoney());
//    System.out.println("触发规则，无优惠");
//end
//
//rule "每满300减30"
//    activation-group "preferential"
//    salience 10
//when
//    $order:Order(money>=300)
//then
//    $order.setPreferential(($order.getMoney()/300)*30);
//    $order.setPay($order.getMoney()-$order.getPreferential());
//    System.out.println("循环满减规则，计算完成 "+$order.toString());
//end